### PR TITLE
[v1.29] Update helm to v3.14.3 

### PR DESCRIPTION
**Pull request by krunalhinguu**
### Updates

- Update `HELM_VERSION`  to `v3.14.3-rancher1`

### Related

- https://github.com/rancher/rancher/issues/43110

### CODE REVIEW

**Comment by mallardduck** [comment]
@krunalhinguu - does this need to be targeted for release in a specific Rancher?

We're currently investigating some changes that may be necessary with shell image to ensure proper k8s support. Based on [helm docs](https://helm.sh/docs/topics/version_skew/), going up to that version will change our k8s support range to: `1.29.x - 1.26.x`. Which for Rancher 2.8 would exclude 1.25 and that would be worse for 2.7 where lower k8s are supported.

**Comment by krunalhinguu** [comment]
I think this is targeted for 1.29 only which is going in 2.9 branch. Also we are not doing any backporting for this one. But i need to confirm these.

@kinarashah any views on this?

**Comment by kinarashah** [comment]
@mallardduck This is targeted for Rancher v2.9.0 milestone. You're right, it'd remove support for lower kubernetes versions, but v2.9.0 is not going to support v1.25. We don't plan on backporting this change to older versions. Are there other changes in shell right now which we need for release/v2.8 branch? In that case, we'd need to branch shell repo and have different tags for different rancher branches.

**Comment by mallardduck** [comment]
@kinarashah - so our team is a bit new to owning `rancher/shell` and we're still sorting out the strategy we'll use. Overall we're probably going to keep the current (albeit flawed) release process and versioning for a bit longer.

Unfortunately switching to "rancher release matching branches" won't actually solve the supportability concern completely though. So we're avoiding making that change until we have a more complete solution for these compatibility concerns.

The gist is that the varying components in Rancher shell each have their own support compatibility rules and they don't always agree with the K8S range that we as Rancher decide to support. Once we have a definitive plan for this in the coming days we'll get this PR merged. 😄

**Comment by mallardduck** [comment]
I have adjusted this PR to point to `release/v2.9` and will create an RC for you on `v0.2.x` for the 2.9.x rancher branch.

**Comment by mallardduck** [comment]
RC for this found here [v0.2.1-rc.1](https://hub.docker.com/layers/rancher/shell/v0.2.1-rc.1/images/sha256-1f0e500c7e483b14bef91850dad1299c36afbf82eca3a8ca2d6014595835e7fe?context=explore)

**Pull request merged**
