### PR TITLE
update release branch for rancher/helm

### PR DESCRIPTION
**Pull request by kinarashah**
https://github.com/rancher/rancher/issues/35511

### CODE REVIEW

**Review by StrongMonkey — APPROVED** [review]

**Comment by brendarearden** [comment]
https://helm.sh/docs/topics/version_skew/#supported-version-skew this looks like it should work for supporting 1.22, but is there a reason we are not doing the latest 3.7.1? I don't see a huge amount of bug fixes from 3.7.0 go 3.7.1 but I was just curious

**Comment by kinarashah** [comment]
@brendarearden that's a good point, I opened this to update commits from helm v3.7.1 to our release-v3.7.0. https://github.com/rancher/helm/pull/33

**Comment by brendarearden** [comment]
The v3.7.1 commits have been added to the release-v3.7.0 branch, so we should be good to merge this now

**Comment by kinarashah** [comment]
@StrongMonkey @brendarearden Could you merge? It looks like I don't have merge permissions here.

**Review by StrongMonkey — APPROVED** [review]

**Pull request merged**
